### ISSUE TITLE
title of the policy should change to : `Activity log alerts should be enabled`

### ISSUE THREAD

**Issue by farchide** [prancer-io/prancer-compliance-test#136]
https://github.com/prancer-io/prancer-compliance-test/blob/e3d9d530af26f06a338987be85eea29495d3cec2/azure/iac/activitylogalerts.rego#L50

The title of the Policy should change to: `Activity log alerts should be enabled` and provide an accurate description
this policy is about enabling the activity log alerts:

```
Indicates whether this activity log alert is enabled. If an activity log alert is not enabled, then none of its actions will be activated.
```

**Comment by rezoan** [comment]
@farchide JUST FYI: Fixed the mentioned issue in PR [https://github.com/prancer-io/prancer-compliance-test/pull/137](https://github.com/prancer-io/prancer-compliance-test/pull/137) and **i could not find any Activity Alert ARM Template** in [https://github.com/prancer-io/prancer-armof](https://github.com/prancer-io/prancer-armof)
`prancer --complience` is ignoring the Activity Log Alert testcase as well, may be due to **missing ARM Template.**
